{
  "revision": "20221025",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "version_module": true,
  "servicePath": "",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "id": "adsense:v2",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "title": "AdSense Management API",
  "rootUrl": "https://adsense.googleapis.com/",
  "version": "v2",
  "resources": {
    "accounts": {
      "methods": {
        "list": {
          "flatPath": "v2/accounts",
          "path": "v2/accounts",
          "httpMethod": "GET",
          "id": "adsense.accounts.list",
          "description": "Lists all accounts available to this user.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ]
        },
        "listChildAccounts": {
          "httpMethod": "GET",
          "id": "adsense.accounts.listChildAccounts",
          "path": "v2/{+parent}:listChildAccounts",
          "description": "Lists all accounts directly managed by the given AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts"
        },
        "get": {
          "flatPath": "v2/accounts/{accountsId}",
          "path": "v2/{+name}",
          "id": "adsense.accounts.get",
          "description": "Gets information about the selected AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "httpMethod": "GET"
        },
        "getAdBlockingRecoveryTag": {
          "httpMethod": "GET",
          "id": "adsense.accounts.getAdBlockingRecoveryTag",
          "flatPath": "v2/accounts/{accountsId}/adBlockingRecoveryTag",
          "path": "v2/{+name}/adBlockingRecoveryTag",
          "description": "Gets the ad blocking recovery tag of an account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ]
        }
      },
      "resources": {
        "adclients": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets the ad client from the given resource name.",
              "path": "v2/{+name}",
              "id": "adsense.accounts.adclients.get"
            },
            "getAdcode": {
              "path": "v2/{+name}/adcode",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634).",
              "id": "adsense.accounts.adclients.getAdcode",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "description": "Lists all the ad clients available in an account.",
              "path": "v2/{+parent}/adclients",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.list",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "urlchannels": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "path": "v2/{+parent}/urlchannels",
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "httpMethod": "GET",
                  "description": "Lists active url channels."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}",
                  "id": "adsense.accounts.adclients.urlchannels.get",
                  "httpMethod": "GET",
                  "description": "Gets information about the selected url channel."
                }
              }
            },
            "customchannels": {
              "methods": {
                "list": {
                  "id": "adsense.accounts.adclients.customchannels.list",
                  "path": "v2/{+parent}/customchannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "description": "Lists all the custom channels available in an ad client."
                },
                "get": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "GET",
                  "description": "Gets information about the selected custom channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}",
                  "id": "adsense.accounts.adclients.customchannels.get"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "adsense.accounts.adclients.customchannels.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "path": "v2/{+name}",
                  "description": "Updates a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product."
                },
                "create": {
                  "description": "Creates a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "POST",
                  "id": "adsense.accounts.adclients.customchannels.create",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "path": "v2/{+parent}/customchannels"
                },
                "delete": {
                  "description": "Deletes a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product.",
                  "httpMethod": "DELETE",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.delete",
                  "path": "v2/{+name}"
                },
                "listLinkedAdUnits": {
                  "description": "Lists all the ad units available for a custom channel.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "path": "v2/{+parent}:listLinkedAdUnits",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits",
                  "httpMethod": "GET"
                }
              }
            },
            "adunits": {
              "methods": {
                "patch": {
                  "id": "adsense.accounts.adclients.adunits.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "PATCH",
                  "description": "Updates an ad unit. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product. For now, this method can only be used to update `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "path": "v2/{+name}"
                },
                "get": {
                  "id": "adsense.accounts.adclients.adunits.get",
                  "path": "v2/{+name}",
                  "description": "Gets an ad unit from a specified account and ad client.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "getAdcode": {
                  "path": "v2/{+name}/adcode",
                  "description": "Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028).",
                  "httpMethod": "GET",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode",
                  "id": "adsense.accounts.adclients.adunits.getAdcode",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "create": {
                  "id": "adsense.accounts.adclients.adunits.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v2/{+parent}/adunits",
                  "description": "Creates an ad unit. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product. Note that ad units can only be created for ad clients with an \"AFC\" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method can only be used to create `DISPLAY` ad units. See: https://support.google.com/adsense/answer/918356[...]",
                  "httpMethod": "POST",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits"
                },
                "listLinkedCustomChannels": {
                  "description": "Lists all the custom channels available for an ad unit.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "path": "v2/{+parent}:listLinkedCustomChannels"
                },
                "list": {
                  "id": "adsense.accounts.adclients.adunits.list",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/adunits",
                  "description": "Lists all ad units under a specified account and ad client.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits"
                }
              }
            }
          }
        },
        "alerts": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists all the alerts available in an account.",
              "path": "v2/{+parent}/alerts",
              "id": "adsense.accounts.alerts.list",
              "flatPath": "v2/accounts/{accountsId}/alerts"
            }
          }
        },
        "sites": {
          "methods": {
            "list": {
              "path": "v2/{+parent}/sites",
              "id": "adsense.accounts.sites.list",
              "flatPath": "v2/accounts/{accountsId}/sites",
              "description": "Lists all the sites available in an account.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "get": {
              "path": "v2/{+name}",
              "description": "Gets information about the selected site.",
              "id": "adsense.accounts.sites.get",
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "reports": {
          "resources": {
            "saved": {
              "methods": {
                "generateCsv": {
                  "description": "Generates a csv formatted saved report.",
                  "path": "v2/{+name}/saved:generateCsv",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "id": "adsense.accounts.reports.saved.generateCsv",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "generate": {
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.reports.saved.generate",
                  "description": "Generates a saved report.",
                  "path": "v2/{+name}/saved:generate",
                  "httpMethod": "GET"
                },
                "list": {
                  "description": "Lists saved reports.",
                  "path": "v2/{+parent}/reports/saved",
                  "id": "adsense.accounts.reports.saved.list",
                  "httpMethod": "GET",
                  "flatPath": "v2/accounts/{accountsId}/reports/saved",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                }
              }
            }
          },
          "methods": {
            "getSaved": {
              "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved",
              "description": "Gets the saved report from the given resource name.",
              "id": "adsense.accounts.reports.getSaved",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+name}/saved"
            },
            "generateCsv": {
              "path": "v2/{+account}/reports:generateCsv",
              "description": "Generates a csv formatted ad hoc report.",
              "httpMethod": "GET",
              "id": "adsense.accounts.reports.generateCsv",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv"
            },
            "generate": {
              "description": "Generates an ad hoc report.",
              "path": "v2/{+account}/reports:generate",
              "id": "adsense.accounts.reports.generate",
              "flatPath": "v2/accounts/{accountsId}/reports:generate",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "payments": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v2/{+parent}/payments",
              "id": "adsense.accounts.payments.list",
              "description": "Lists all the payments available for an account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/payments"
            }
          }
        }
      }
    }
  },
  "ownerName": "Google",
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.",
  "name": "adsense",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://adsense.googleapis.com/"
}
