{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.policy.readonly": {
          "description": "See policies applied to Chrome OS and Chrome Browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.policy": {
          "description": "See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization"
        }
      }
    }
  },
  "title": "Chrome Policy API",
  "basePath": "",
  "mtlsRootUrl": "https://chromepolicy.mtls.googleapis.com/",
  "name": "chromepolicy",
  "description": "The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.",
  "documentationLink": "http://developers.google.com/chrome/policy",
  "id": "chromepolicy:v1",
  "baseUrl": "https://chromepolicy.googleapis.com/",
  "kind": "discovery#restDescription",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "rootUrl": "https://chromepolicy.googleapis.com/",
  "ownerName": "Google",
  "protocol": "rest",
  "canonicalName": "Chrome Policy",
  "ownerDomain": "google.com",
  "version_module": true,
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "supportsMediaUpload": true,
          "description": "Creates an enterprise file from the content provided by user. Returns a public download url for end user.",
          "id": "chromepolicy.media.upload",
          "httpMethod": "POST",
          "flatPath": "v1/customers/{customersId}/policies/files:uploadPolicyFile",
          "scopes": [
            "https://www.googleapis.com/auth/chrome.management.policy"
          ],
          "path": "v1/{+customer}/policies/files:uploadPolicyFile"
        }
      }
    },
    "customers": {
      "resources": {
        "policies": {
          "methods": {
            "resolve": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/policies:resolve",
              "path": "v1/{+customer}/policies:resolve",
              "id": "chromepolicy.customers.policies.resolve",
              "httpMethod": "POST",
              "description": "Gets the resolved policy values for a list of policies that match a search query."
            }
          },
          "resources": {
            "networks": {
              "methods": {
                "defineNetwork": {
                  "description": "Define a new network.",
                  "path": "v1/{+customer}/policies/networks:defineNetwork",
                  "id": "chromepolicy.customers.policies.networks.defineNetwork",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/policies/networks:defineNetwork"
                },
                "removeCertificate": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "description": "Remove an existing certificate by guid.",
                  "id": "chromepolicy.customers.policies.networks.removeCertificate",
                  "flatPath": "v1/customers/{customersId}/policies/networks:removeCertificate",
                  "path": "v1/{+customer}/policies/networks:removeCertificate"
                },
                "removeNetwork": {
                  "id": "chromepolicy.customers.policies.networks.removeNetwork",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "flatPath": "v1/customers/{customersId}/policies/networks:removeNetwork",
                  "description": "Remove an existing network by guid.",
                  "path": "v1/{+customer}/policies/networks:removeNetwork"
                },
                "defineCertificate": {
                  "description": "Creates a certificate at a specified OU for a customer.",
                  "path": "v1/{+customer}/policies/networks:defineCertificate",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "flatPath": "v1/customers/{customersId}/policies/networks:defineCertificate",
                  "id": "chromepolicy.customers.policies.networks.defineCertificate",
                  "httpMethod": "POST"
                }
              }
            },
            "orgunits": {
              "methods": {
                "batchInherit": {
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchInherit",
                  "description": "Modify multiple policy values that are applied to a specific org unit so that they now inherit the value from a parent (if applicable). All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "path": "v1/{+customer}/policies/orgunits:batchInherit",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "id": "chromepolicy.customers.policies.orgunits.batchInherit",
                  "httpMethod": "POST"
                },
                "batchModify": {
                  "path": "v1/{+customer}/policies/orgunits:batchModify",
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchModify",
                  "httpMethod": "POST",
                  "description": "Modify multiple policy values that are applied to a specific org unit. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "id": "chromepolicy.customers.policies.orgunits.batchModify",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ]
                }
              }
            },
            "groups": {
              "methods": {
                "batchModify": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "path": "v1/{+customer}/policies/groups:batchModify",
                  "flatPath": "v1/customers/{customersId}/policies/groups:batchModify",
                  "httpMethod": "POST",
                  "id": "chromepolicy.customers.policies.groups.batchModify",
                  "description": "Modify multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status."
                },
                "listGroupPriorityOrdering": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy",
                    "https://www.googleapis.com/auth/chrome.management.policy.readonly"
                  ],
                  "path": "v1/{+customer}/policies/groups:listGroupPriorityOrdering",
                  "flatPath": "v1/customers/{customersId}/policies/groups:listGroupPriorityOrdering",
                  "description": "Retrieve a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status.",
                  "id": "chromepolicy.customers.policies.groups.listGroupPriorityOrdering",
                  "httpMethod": "POST"
                },
                "batchDelete": {
                  "description": "Delete multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "id": "chromepolicy.customers.policies.groups.batchDelete",
                  "path": "v1/{+customer}/policies/groups:batchDelete",
                  "flatPath": "v1/customers/{customersId}/policies/groups:batchDelete",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ]
                },
                "updateGroupPriorityOrdering": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "flatPath": "v1/customers/{customersId}/policies/groups:updateGroupPriorityOrdering",
                  "httpMethod": "POST",
                  "id": "chromepolicy.customers.policies.groups.updateGroupPriorityOrdering",
                  "path": "v1/{+customer}/policies/groups:updateGroupPriorityOrdering",
                  "description": "Update a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status."
                }
              }
            }
          }
        },
        "policySchemas": {
          "methods": {
            "list": {
              "id": "chromepolicy.customers.policySchemas.list",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "path": "v1/{+parent}/policySchemas",
              "description": "Gets a list of policy schemas that match a specified filter value for a given customer.",
              "flatPath": "v1/customers/{customersId}/policySchemas",
              "httpMethod": "GET"
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/policySchemas/{policySchemasId}",
              "description": "Get a specific policy schema for a customer by its resource name.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "id": "chromepolicy.customers.policySchemas.get"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "revision": "20221020"
}
